### PR TITLE
feature(repository): Adding the ability to define tablename at runtime

### PR DESCRIPTION
**Pull request by gonzoga**
# Description

allowing for defining a tablename during repository call so we can handle the case where a client would want a tablename per environment. 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Added unit tests based on existing tests but uses the new parameter added specifying tablename

**Test Configuration**:
Dockerized Dynamodb instance with unit test runner.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by marcodafonseca** [comment]
I was thinking of a slightly different approach as it is a far smaller change to the code base life the following:
image

What do you think? Will this work for the project you are working on?

**Comment by marcodafonseca** [comment]
I've given it some more thought and realized that my suggestion won't work for all scenarios. Will review your PR properly now

**Comment by gonzoga** [comment]
Just saw your comments. What you suggested should work for our use case. What scenarios are you thinking it won't work for?

**Comment by marcodafonseca** [comment]
It won't work when trying to get data from Dynamo as you only pass in a type there, not an instantiated object that would otherwise have a tablename allocated

**Review by marcodafonseca — APPROVED** [review]

**Comment by gonzoga** [comment]
Oh yeah thats a good point. Well thank you so much for the review!

**Pull request merged**
